In [41]:
import pandas as pd
import numpy as np
import random

In [42]:
data = pd.read_csv('Data/data.csv')

In [43]:
data=data[:2800]

In [44]:
data=data.drop(data.columns[0],axis=1)

In [45]:
data

pipe-dia  pipe-mat  pipe-bd  先前失效  pipe-pre  pipe-len  pipe-age  a7
0     0.285714         2   0.6875     0  0.416667  0.028876  0.000000   0
1     0.285714         2   0.6250     0  0.708333  0.014238  0.296296   0
2     0.285714         2   0.0625     0  0.166667  0.061288  0.166667   0
3     0.285714         2   0.5625     0  0.375000  0.054916  0.185185   0
4     0.285714         2   0.3125     0  0.083333  0.070940  0.185185   0
...        ...       ...      ...   ...       ...       ...       ...  ..
2795  0.285714         1   0.3150     1  0.416667  0.389229  0.444444   1
2796  0.285714         6   0.3175     0  0.375000  0.138432  0.537037   1
2797  0.285714         6   0.1250     1  0.125000  1.000000  0.407407   1
2798  0.285714         6   0.1250     0  0.583333  0.002582  0.574074   1
2799  0.285714         6   0.5000     0  0.458333  0.030858  0.629630   1

[2800 rows x 8 columns]

In [46]:
from sklearn.preprocessing import OneHotEncoder

In [47]:
columns_to_encoder=['pipe-mat','先前失效']
columns_to_encoder

['pipe-mat', '先前失效']

In [48]:
encoder=OneHotEncoder(sparse=False)

In [49]:
encode_data=encoder.fit_transform(data[columns_to_encoder])

C:\Users\康云凯\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [50]:
encode_data

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [51]:
encoded_df=pd.DataFrame(encode_data,columns=encoder.get_feature_names_out(columns_to_encoder))

In [52]:
data=pd.concat([data,encoded_df],axis=1)

In [53]:
data

pipe-dia  pipe-mat  pipe-bd  先前失效  pipe-pre  pipe-len  pipe-age  a7  \
0     0.285714         2   0.6875     0  0.416667  0.028876  0.000000   0   
1     0.285714         2   0.6250     0  0.708333  0.014238  0.296296   0   
2     0.285714         2   0.0625     0  0.166667  0.061288  0.166667   0   
3     0.285714         2   0.5625     0  0.375000  0.054916  0.185185   0   
4     0.285714         2   0.3125     0  0.083333  0.070940  0.185185   0   
...        ...       ...      ...   ...       ...       ...       ...  ..   
2795  0.285714         1   0.3150     1  0.416667  0.389229  0.444444   1   
2796  0.285714         6   0.3175     0  0.375000  0.138432  0.537037   1   
2797  0.285714         6   0.1250     1  0.125000  1.000000  0.407407   1   
2798  0.285714         6   0.1250     0  0.583333  0.002582  0.574074   1   
2799  0.285714         6   0.5000     0  0.458333  0.030858  0.629630   1   

      pipe-mat_0  pipe-mat_1  pipe-mat_2  pipe-mat_3  pipe-mat_4  pipe-mat_5  \
0            0.0         0.0         1.0         0.0         0.0         0.0   
1            0.0         0.0         1.0         0.0         0.0         0.0   
2            0.0         0.0         1.0         0.0         0.0         0.0   
3            0.0         0.0         1.0         0.0         0.0         0.0   
4            0.0         0.0         1.0         0.0         0.0         0.0   
...          ...         ...         ...         ...         ...         ...   
2795         0.0         1.0         0.0         0.0         0.0         0.0   
2796         0.0         0.0         0.0         0.0         0.0         0.0   
2797         0.0         0.0         0.0         0.0         0.0         0.0   
2798         0.0         0.0         0.0         0.0         0.0         0.0   
2799         0.0         0.0         0.0         0.0         0.0         0.0   

      pipe-mat_6  先前失效_0  先前失效_1  
0            0.0     1.0     0.0  
1            0.0     1.0     0.0  
2            0.0     1.0     0.0  
3            0.0     1.0     0.0  
4            0.0     1.0     0.0  
...          ...     ...     ...  
2795         0.0     0.0     1.0  
2796         1.0     1.0     0.0  
2797         1.0     0.0     1.0  
2798         1.0     1.0     0.0  
2799         1.0     1.0     0.0  

[2800 rows x 17 columns]

In [54]:
data=data.drop(data.columns[1],axis=1)

In [55]:
data=data.drop(data.columns[2],axis=1)

In [56]:
data

pipe-dia  pipe-bd  pipe-pre  pipe-len  pipe-age  a7  pipe-mat_0  \
0     0.285714   0.6875  0.416667  0.028876  0.000000   0         0.0   
1     0.285714   0.6250  0.708333  0.014238  0.296296   0         0.0   
2     0.285714   0.0625  0.166667  0.061288  0.166667   0         0.0   
3     0.285714   0.5625  0.375000  0.054916  0.185185   0         0.0   
4     0.285714   0.3125  0.083333  0.070940  0.185185   0         0.0   
...        ...      ...       ...       ...       ...  ..         ...   
2795  0.285714   0.3150  0.416667  0.389229  0.444444   1         0.0   
2796  0.285714   0.3175  0.375000  0.138432  0.537037   1         0.0   
2797  0.285714   0.1250  0.125000  1.000000  0.407407   1         0.0   
2798  0.285714   0.1250  0.583333  0.002582  0.574074   1         0.0   
2799  0.285714   0.5000  0.458333  0.030858  0.629630   1         0.0   

      pipe-mat_1  pipe-mat_2  pipe-mat_3  pipe-mat_4  pipe-mat_5  pipe-mat_6  \
0            0.0         1.0         0.0         0.0         0.0         0.0   
1            0.0         1.0         0.0         0.0         0.0         0.0   
2            0.0         1.0         0.0         0.0         0.0         0.0   
3            0.0         1.0         0.0         0.0         0.0         0.0   
4            0.0         1.0         0.0         0.0         0.0         0.0   
...          ...         ...         ...         ...         ...         ...   
2795         1.0         0.0         0.0         0.0         0.0         0.0   
2796         0.0         0.0         0.0         0.0         0.0         1.0   
2797         0.0         0.0         0.0         0.0         0.0         1.0   
2798         0.0         0.0         0.0         0.0         0.0         1.0   
2799         0.0         0.0         0.0         0.0         0.0         1.0   

      先前失效_0  先前失效_1  
0        1.0     0.0  
1        1.0     0.0  
2        1.0     0.0  
3        1.0     0.0  
4        1.0     0.0  
...      ...     ...  
2795     0.0     1.0  
2796     1.0     0.0  
2797     0.0     1.0  
2798     1.0     0.0  
2799     1.0     0.0  

[2800 rows x 15 columns]

In [57]:
data=data.rename(columns={'a7':'label'})

In [58]:
data

pipe-dia  pipe-bd  pipe-pre  pipe-len  pipe-age  label  pipe-mat_0  \
0     0.285714   0.6875  0.416667  0.028876  0.000000      0         0.0   
1     0.285714   0.6250  0.708333  0.014238  0.296296      0         0.0   
2     0.285714   0.0625  0.166667  0.061288  0.166667      0         0.0   
3     0.285714   0.5625  0.375000  0.054916  0.185185      0         0.0   
4     0.285714   0.3125  0.083333  0.070940  0.185185      0         0.0   
...        ...      ...       ...       ...       ...    ...         ...   
2795  0.285714   0.3150  0.416667  0.389229  0.444444      1         0.0   
2796  0.285714   0.3175  0.375000  0.138432  0.537037      1         0.0   
2797  0.285714   0.1250  0.125000  1.000000  0.407407      1         0.0   
2798  0.285714   0.1250  0.583333  0.002582  0.574074      1         0.0   
2799  0.285714   0.5000  0.458333  0.030858  0.629630      1         0.0   

      pipe-mat_1  pipe-mat_2  pipe-mat_3  pipe-mat_4  pipe-mat_5  pipe-mat_6  \
0            0.0         1.0         0.0         0.0         0.0         0.0   
1            0.0         1.0         0.0         0.0         0.0         0.0   
2            0.0         1.0         0.0         0.0         0.0         0.0   
3            0.0         1.0         0.0         0.0         0.0         0.0   
4            0.0         1.0         0.0         0.0         0.0         0.0   
...          ...         ...         ...         ...         ...         ...   
2795         1.0         0.0         0.0         0.0         0.0         0.0   
2796         0.0         0.0         0.0         0.0         0.0         1.0   
2797         0.0         0.0         0.0         0.0         0.0         1.0   
2798         0.0         0.0         0.0         0.0         0.0         1.0   
2799         0.0         0.0         0.0         0.0         0.0         1.0   

      先前失效_0  先前失效_1  
0        1.0     0.0  
1        1.0     0.0  
2        1.0     0.0  
3        1.0     0.0  
4        1.0     0.0  
...      ...     ...  
2795     0.0     1.0  
2796     1.0     0.0  
2797     0.0     1.0  
2798     1.0     0.0  
2799     1.0     0.0  

[2800 rows x 15 columns]

In [59]:
cols=data.columns.tolist()

In [60]:
cols.append(cols.pop(5))

In [61]:
cols

['pipe-dia',
 'pipe-bd',
 'pipe-pre',
 'pipe-len',
 'pipe-age',
 'pipe-mat_0',
 'pipe-mat_1',
 'pipe-mat_2',
 'pipe-mat_3',
 'pipe-mat_4',
 'pipe-mat_5',
 'pipe-mat_6',
 '先前失效_0',
 '先前失效_1',
 'label']

In [62]:
data=data[cols]

In [63]:
label=data['label']

In [64]:
label=label.values

In [65]:
np.count_nonzero(label)

408

In [66]:
import scipy.sparse as sparse

In [67]:
label

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [68]:
def generate_adjacency_matrix(num_nodes,max_neighbors):
    adjacency_matrix=np.zeros((num_nodes,num_nodes))
    for node in range(num_nodes):
        num_neighbors=random.randint(1,max_neighbors)
        neighbors=random.sample(range(num_nodes),num_neighbors)
        adjacency_matrix[node,neighbors]=1
        adjacency_matrix[neighbors,node]=1

    return adjacency_matrix
num_nodes=2800
max_neighbors=3

adjancency_matrix=generate_adjacency_matrix(num_nodes,max_neighbors)
adjancency_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [69]:
Network=sparse.coo_matrix(adjancency_matrix)

In [70]:
Network

<2800x2800 sparse matrix of type '<class 'numpy.float64'>'
	with 11290 stored elements in COOrdinate format>

In [71]:

atr_data=data.drop(data.columns[-1],axis=1)
Attributes=atr_data.values

In [72]:
Attributes=sparse.coo_matrix(Attributes)

In [73]:
Attributes

<2800x14 sparse matrix of type '<class 'numpy.float64'>'
	with 19451 stored elements in COOrdinate format>

In [74]:
Class=np.zeros((2800,1))

In [75]:
Class

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [76]:
import scipy.io

In [77]:
data={'Network':Network,'Attributes':Attributes,'Label':label,'Class':Class}

In [78]:
scipy.io.savemat('data.mat',data)

In [79]:
data = scipy.io.loadmat('data.mat')

In [80]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Jun 28 19:52:24 2023',
 '__version__': '1.0',
 '__globals__': [],
 'Network': <2800x2800 sparse matrix of type '<class 'numpy.float64'>'
 	with 11290 stored elements in Compressed Sparse Column format>,
 'Attributes': <2800x14 sparse matrix of type '<class 'numpy.float64'>'
 	with 19451 stored elements in Compressed Sparse Column format>,
 'Label': array([[0, 0, 0, ..., 1, 1, 1]], dtype=int64),
 'Class': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])}

In [81]:
data = scipy.io.loadmat('data.mat')

In [82]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Jun 28 20:38:01 2023',
 '__version__': '1.0',
 '__globals__': [],
 'Network': <2800x2800 sparse matrix of type '<class 'numpy.float64'>'
 	with 11400 stored elements in Compressed Sparse Column format>,
 'Attributes': <2800x14 sparse matrix of type '<class 'numpy.float64'>'
 	with 19455 stored elements in Compressed Sparse Column format>,
 'Label': array([[0, 0, 1, ..., 0, 0, 0]], dtype=int64),
 'Class': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])}

In [92]:
str1='data_{}.mat'.format(1)

In [93]:
str1

'data_1.mat'

In [98]:
data = scipy.io.loadmat('data.mat')
data

FileNotFoundError: [Errno 2] No such file or directory: 'data.mat'

In [99]:
data04=scipy.io.loadmat('data_4.mat')

In [100]:
data04

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Jun 28 21:02:07 2023',
 '__version__': '1.0',
 '__globals__': [],
 'Network': <1582x1582 sparse matrix of type '<class 'numpy.float64'>'
 	with 6308 stored elements in Compressed Sparse Column format>,
 'Attributes': <1582x14 sparse matrix of type '<class 'numpy.float64'>'
 	with 10986 stored elements in Compressed Sparse Column format>,
 'Label': array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 'Class': array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])}

In [1]:
def sample_subgraphs(adj_matrix,feature_matrix,num_graphs,subgraph_size):
    num_nodes=adj_matrix.shape[0]
    sampled_num_nodes=[]

    for i in range(num_graphs):
        while True:
            start_node = np.random.randint(num_nodes)
            if start_node not in sampled_num_nodes:



IndentationError: expected an indented block after 'if' statement on line 8 (136765523.py, line 9)

In [45]:
import numpy as np
data=np.load('data.npz')

In [46]:
data['train_mask']

array([ True,  True,  True, ..., False, False, False])

In [51]:
np.count_nonzero(data['label'][data['vaild_mask']])

820